[project]
name = "rhbu-llama-stack-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fire==0.7.1",
    "llama-stack-client==0.2.8",
    "requests==2.32.5",
]
